### ISSUE TITLE
Missing GenkiRyS

### ISSUE THREAD

**Issue by TraceStar** [CAPTAINGROSCHEH/IRyS-noises-website#3]
The quintessential GenkiRyS is missing from the audio list. I have helpfully shared a link to said file.

https://files.catbox.moe/gccot4.mp3

**Comment by walidodev** [comment]
Oh of course! Thanks for the submission, I'll add it with some other audio files that I needed to add too!

**Comment by walidodev** [comment]
Added as "Genki" !
